{-# LANGUAGE OverloadedStrings #-}

{- | What both Producer test modules need: a key, generated events, and a chain
built out of them.

The chaining lives here rather than in either test because it is the thing under
test in neither — it is how a caller is meant to use
'EventChain.Produce.produce', written once so both modules exercise the same
usage rather than two approximations of it.
-}
module Test.EventChain.Fixtures
    ( producerKey
    , producerClaim
    , genEvent
    , genLabel
    , genLabelWith
    , chainFrom
    , unhex
    ) where

import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import Data.ByteString.Char8 qualified as C8
import Data.Char (digitToInt, isHexDigit)
import Data.Text (Text)
import EventChain
import EventChain.Crypto (PrivateKey, privateKey, privateKeyPublic)
import EventChain.Crypto.Types (ClaimedKey, payloadHashFromBytes)
import Hedgehog (Gen)
import Hedgehog.Gen qualified as Gen
import Hedgehog.Range qualified as Range

{- | The Producer these tests sign with: RFC 6979 A.2.5's private key.

Published, so the fixture is a number someone else wrote down, and fixed, so an
AOF built from the same events is the same bytes every run — 'produce' is pure
and the nonce is deterministic (ADR-0004), so there is nothing here that needs
seeding or a temp file to be reproducible.

Only its validity is load-bearing. These tests check the Producer's format, not
its arithmetic; whether the RFC's key yields the RFC's signatures is
@eventchain-crypto@'s known-answer test and is settled before this file runs.
-}
producerKey :: PrivateKey
producerKey = case privateKey (unhex "C9AFA9D845BA75166B5C215767B1D6934E50C3DB36E89B127B8A622B120F6721") of
    Right k -> k
    Left err -> error ("RFC 6979's own key was rejected: " <> show err)

-- | The point that key derives, as a line carries it.
producerClaim :: ClaimedKey
producerClaim = privateKeyPublic producerKey

{- | An event with an arbitrary commitment and a placeholder @prevHash@.

'chainFrom' overwrites the linkage, so what is generated here is only the
event's own content. Callers pass the label generator because what counts as a
hostile label depends on who is grading the output.
-}
genEvent :: Gen Text -> Gen ChainedEvent
genEvent label = do
    eid <- label
    ref <- label
    digest <- Gen.bytes (Range.singleton 32)
    pure
        ChainedEvent
            { entryId = entryId eid
            , payloadHash = hashOf digest
            , payloadRef = payloadRef ref
            , prevHash = genesisHash
            , kind = Lifecycle
            }
  where
    hashOf bs = case payloadHashFromBytes bs of
        Right h -> h
        Left err -> error ("32 generated bytes were refused as a digest: " <> show err)

{- | Text weighted toward what breaks an encoder: the JSON escapes, the C0
range, and the astral planes.

@entry_id@ and @payload_ref@ are producer-chosen and carry no encoding
requirement (@docs/paper-amendments.md@ PA-03), so all of this can reach a line
and the encoder has no right to assume otherwise.
-}
genLabel :: Gen Text
genLabel = genLabelWith (const True)

{- | 'genLabel', narrowed to characters a caller can cope with.

One distribution, restricted at the edge, rather than a second one written out
next to whoever needed the restriction — a copy would keep its own idea of what
is hostile, and quietly stop widening when this one does.

The predicate is a concession to the grader and never to the Producer. Anything
excluded here is text the format still permits, so an exclusion is a statement
about the test's oracle that the caller owes a reason for.
-}
genLabelWith :: (Char -> Bool) -> Gen Text
genLabelWith acceptable = Gen.text (Range.linear 0 24) (Gen.filter acceptable genChar)
  where
    genChar =
        Gen.frequency
            [ (5, Gen.unicode)
            , (2, Gen.element ['"', '\\', '/', ' ', '\t', '\n', '\r'])
            , (1, Gen.enum '\x00' '\x1f')
            ]

{- | Produce a chain: the first event from genesis, each one after linked to the
line before it.

This is the intended use of 'EventChain.Produce.produce' spelled out — the
caller carries @lineHash@ forward into the next @prevHash@ and nothing else.
Note what it does /not/ do: it never recomputes a digest from an event, because
the digest belongs to the line that was written.

Errors rather than returning an 'Either': a Producer that cannot sign with a key
libcrypto already accepted is a broken test, not a finding.
-}
chainFrom :: PrivateKey -> [ChainedEvent] -> [ProducedLine]
chainFrom key = go genesisHash
  where
    go _ [] = []
    go prev (event : rest) = case produce key event{prevHash = prev} of
        Right p -> p : go p.lineHash rest
        Left err -> error ("produce failed on a key libcrypto accepted: " <> show err)

{- | Read a constant as its document prints it.

Errors loudly, because a malformed constant is a broken test rather than a
finding — the same call @eventchain-crypto@'s known-answer tests make, and made
separately because a test suite cannot import another package's.
-}
unhex :: ByteString -> ByteString
unhex t
    | odd (C8.length t) = error ("unhex: odd length in " <> show t)
    | not (C8.all isHexDigit t) = error ("unhex: not hex: " <> show t)
    | otherwise = BS.pack (go (C8.unpack t))
  where
    go (a : b : r) = fromIntegral (digitToInt a * 16 + digitToInt b) : go r
    go _ = []
