{-# LANGUAGE OverloadedStrings #-}

{- | The committed AOF vector: what this Producer emits, frozen as bytes at the
top of the repository.

The vector exists because of a wall. @eventchain-verify@ may not depend on
@eventchain@ — @gates:verifier-independence@ walks the resolved install plan and
seeds on /every/ unit of that package, test suites included — so the Verifier's
tests cannot ask the Producer for an AOF to read. A file is how the Producer's
output crosses to a reader that has never seen its source, and that crossing is
the whole point: "the Producer's output verifies" is then a claim about the
format rather than about a shared function.

/Why a golden test rather than a generator the Verifier runs./ Because the file
must be a fixed artifact for a stranger to check against, and because nothing
else would notice if the two drifted. This test is what makes the committed
bytes still true: it rebuilds them from the same fixed events and compares. It
can do that only because there is nothing to seed — 'EventChain.Produce.produce'
is pure and ADR-0004's nonce is RFC 6979's, so the same events under the same
key are the same bytes forever.

The events are fixed rather than generated for the same reason. Breadth over
event content belongs to the property tests, which run hundreds of cases and
commit nothing; a vector's job is to be one thing that does not move.
-}
module Test.EventChain.Vectors
    ( tests
    , vectorAof
    , vectorPath
    , findRepoRoot
    ) where

import Data.ByteString (ByteString)
import Data.ByteString qualified as BS
import EventChain
import EventChain.Crypto.Types (lineBytesRaw, payloadHashFromBytes)
import System.Directory (doesFileExist, getCurrentDirectory)
import System.FilePath (takeDirectory, (</>))
import Test.EventChain.Fixtures (chainFrom, producerKey, unhex)
import Test.Tasty (TestTree, testGroup)
import Test.Tasty.HUnit (assertFailure, testCase, (@?=))

tests :: TestTree
tests =
    testGroup
        "Test.EventChain.Vectors"
        [testCase "the committed vector is what the Producer emits" vectorIsCurrent]

{- | Where the vector lives, relative to the repository root.

At the top of the repo rather than inside either package, because both sides
face it and neither owns it: @eventchain@ generates it and @eventchain-verify@
adjudicates it (@docs/plan.md@).
-}
vectorPath :: FilePath
vectorPath = "vectors" </> "v0-lifecycle.jsonl"

{- | The committed bytes are still what this Producer writes.

Fails with the reason rather than a diff of 400 columns of base64: what a reader
needs first is /that/ the format moved, and the two files are there to be looked
at. A failure here is one of two findings, and they are not the same: either a
deliberate format change needs the vector regenerated and every downstream
verifier told, or the Producer changed what it emits and nobody meant it to.
-}
vectorIsCurrent :: IO ()
vectorIsCurrent = do
    root <- findRepoRoot
    let path = root </> vectorPath
    exists <- doesFileExist path
    if not exists
        then
            assertFailure . unlines $
                [ "No vector at " <> path <> "."
                , ""
                , "The Verifier's tests read this file; it is not generated on demand,"
                , "because a file regenerated by the thing it grades is not evidence."
                ]
        else do
            committed <- BS.readFile path
            committed @?= vectorAof

{- | The vector's bytes: the AOF these fixed events produce under the fixed key.

Terminated per [JSON Lines](https://jsonlines.org/) §3 — every line, including
the last, ends in @0x0a@. The final terminator is optional in the format and
present here on purpose: a vector should be the ordinary case, and a reader that
mishandles the optional-trailing-newline rule should fail on a file that has one
rather than on one that does not.
-}
vectorAof :: ByteString
vectorAof = BS.concat [lineBytesRaw p.line <> "\n" | p <- chainFrom producerKey vectorEvents]

{- | The events the vector is built from, chosen to exercise what a reader gets
wrong.

Labels carry no encoding requirement (@docs/paper-amendments.md@ PA-03), so the
vector spends them: quotes and backslashes, the two escapes RFC 8785 §3.2.2.2
spells @\\b@ and @\\f@ where a general JSON encoder may emit @\\u0008@ and
@\\u000c@, C0 controls, non-ASCII text and an astral-plane character that is a
surrogate pair in UTF-16 and four bytes in UTF-8.

A third-party verifier that passes this file has read the escaping rules
correctly. One that reads them as "whatever my JSON library does" fails on line
four, which is the point of putting it here rather than in a property test that
commits nothing.
-}
vectorEvents :: [ChainedEvent]
vectorEvents =
    [ event "evt-001" "aof/2026-07/001" "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    , event "evt-002 \"quoted\" and back\\slashed" "aof/2026-07/002" "5891b5b522d5df086d0ff0b110fbd9d21bb4fc7163af34d08286a2e846f6be03"
    , event "evt-003 café 日本語 𝔘" "aof/2026-07/003" "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b"
    , event "evt-004 \b\f\n\r\t\x00\x1f" "aof/2026-07/004" "d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35"
    ]
  where
    -- prevHash is a placeholder: `chainFrom` overwrites it with the linkage,
    -- because the chain's state is the digest of the line that was written.
    event eid ref digest =
        ChainedEvent
            { entryId = entryId eid
            , payloadHash = hashOf digest
            , payloadRef = payloadRef ref
            , prevHash = genesisHash
            , kind = Lifecycle
            }

    hashOf hex = case payloadHashFromBytes (unhex hex) of
        Right h -> h
        Left err -> error ("a vector's payload hash is not 32 bytes: " <> show err)

{- | The directory holding @cabal.project@, found by walking up.

Cabal runs a test suite from its own package directory, and the vector is a
project-level artifact rather than this package's. Written here rather than
shared with the Verifier's copy of the same six lines: a test-suite helper is not
format logic, and a package that could import the other's helpers is a package
that could import its canonicalizer.
-}
findRepoRoot :: IO FilePath
findRepoRoot = getCurrentDirectory >>= go
  where
    go dir = do
        found <- doesFileExist (dir </> "cabal.project")
        if found
            then pure dir
            else
                let up = takeDirectory dir
                 in if up == dir
                        then error "No cabal.project above the working directory."
                        else go up
